export const AUTHENTICATION_SCREEN = "AUTHENTICATION_SCREEN";
export const MAIN_SCREEN = "MAIN_SCREEN";
export const NEWS_SCREEN = "NEWS_SCREEN";
export const SECTION_SCREEN = "SECTION_SCREEN";
export const SUB_SECTION_SCREEN = "SUB_SECTION_SCREEN";
export const REPORTS_SCREEN = "REPORTS_SCREEN";
export const REPORTS_DETAIL_SCREEN = "REPORTS_DETAIL_SCREEN";
export const PROFILE_SCREEN = "PROFILE_SCREEN";

export const AUTHENTICATION_STACK = "AUTHENTICATION_STACK";
export const MAIN_STACK = "MAIN_STACK";
export const NEWS_STACK = "NEWS_STACK";
export const PROFILE_STACK = "PROFILE_STACK";

export const TAB_NAVIGATOR = "TAB_NAVIGATOR";

export const QR_SCANER_SCREEN = "QR_SCANER_SCREEN";